### ISSUE TITLE
Input issue on Android

### ISSUE THREAD

**Issue by graciek** [critrolesync/critrolesync.github.io#2]
When i use the site on Chrome on Android, I cannot select the colon which is required in the input field:

![screenshot_20200629-194214](https://user-images.githubusercontent.com/20226157/86044100-8aa60c80-ba41-11ea-89d2-6e43f12e8bbf.jpg)

I believe this is being caused by `inputmode="numeric"` attribute being set on the input field as the numeric keypad is being forced to appear instead of the regular keypad

**Comment by jpgill86** [comment]
Thanks for reporting @graciek!

You are right, that bit of code was forcing the numeric keyboard. My mobile numeric keyboard is different from yours and includes a colon button. I shouldn't have assumed everyone's would. I've fixed it, and the change is now live. You may need to do a hard refresh of the page to load it.

Thanks again!
